.\" (C) Copyright 2024 Raphaël Halimi <raphael.halimi@gmail.com>

.TH SHELL-SCRIPT-HELPER-TEMPLATE.CONF 5 "2024-08-09"

.SH NAME
shell-script-helper-template.conf \- \fBshell-script-helper-template\fR
configuration file

.SH SYNOPSIS
.TP
.B /etc/shell-script-helper-template.conf
system-wide
.TP
.B ~/.shell-script-helper-template.conf
per-user

.SH DESCRIPTION
The \fIshell-script-helper-template.conf\fR configuration files are sourced by
the \fBshell-script-helper-template\fR shell script to set some default
variables.
.PP
The system-wide configuration file overrides the script defaults; the per-user
configuration file overrides the system-wide configuration file; and finally,
the command-line options override the per-user configuration file.

.SH VARIABLES
The following variables are used in the script:
.TP
.B CRSS_FULLNAME
Your full name, default is $USER.
.TP
.B CRSS_EMAIL
Your e-mail address, default is $USER@hostname.
.TP
.B VERBOSE
Set to 1 to enable verbose mode, default is 0.
.TP
.B DEBUG
Set to 1 to enable debug mode, default is 0.

.SH EXAMPLE
.nf
.RS
# Configuration file for shell-script-helper-template
# See the shell-script-helper-template.conf(5) manpage for details

VERBOSE=1
DEBUG=0
CRSS_FULLNAME="John Doe"
CRSS_EMAIL="jdoe@bar.com"
.RE
.fi

.SH SEE ALSO
.BR shell-script-helper-template (1).
